### ISSUE TITLE
Use operators for `set` and `set_mut`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/quack#24]
@eddyb Suggested `|` for `set` and `<<` for set_mut.

**Comment by eddyb** [comment]
Also `+` and `+=`, but we can't overload the latter yet ;(.

**Comment by bvssvni** [comment]
I don't think adding operators for this will make it more intuitive to use.

**Comment by bvssvni** [comment]
We could use operators to generate tuples, and then call `.set` at the end.

For example:

``` Rust
button.set_mut(Label("click me") | Position([0, 0]));
```
