### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by Potpourri** [PistonDevelopers/quack#54]
Rust more doesn't allow impl foreign trait for arbitrary type. We more can't use (T, U). What the plans on this crate? As far as I know quack should remove from piston-core libraries, but still uses in graphics. I would like to rewrite it to use user's type instead (T, U).
@bvssvni what do you think of it?

**Comment by bvssvni** [comment]
I think we'll have to rewrite graphics and Conrod to replace piston-quack.

**Comment by Potpourri** [comment]
I agree. Need to divide the work.

**Comment by dcampbell24** [comment]
I think this is the relevant RFC: https://github.com/rust-lang/rfcs/pull/1023

**Comment by bvssvni** [comment]
I'll open issues and assign myself to them when working on a repo.
